[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  # Aquí se define la configuración global para todas las funciones
  # de Python en tu proyecto.
  [functions.python]
    python_version = "3.9"


